import { TierListEntry } from "../remotion/TierListVideo";

export type PresetTierList = {
  id: string;
  title: string;
  tiktokCaption?: string;
  videoType?: "tier-list" | "top5"; // デフォルトはtier-list
  entries: Omit<TierListEntry, "imageUrl" | "ttsUrl">[]; // imageUrlとttsUrlは動的に付与する
};

export const PRESET_TIER_LISTS: PresetTierList[] = [
  {
    id: "psychopath",
    title: "真のサイコパスランキング",
    tiktokCaption: "あなたの周りにも絶対いるヤバい奴…😱 当たってたらコメントで教えて！\n\n#MBTI #MBTI診断 #16タイプ診断 #サイコパス #性格診断 #性格テスト",
    entries: [
      { mbtiType: "ESFJ", tier: "D", comment: "他人の痛みに共感しすぎて自分が泣くタイプ" },
      { mbtiType: "ISFJ", tier: "D", comment: "優しすぎてサイコパスの餌食になりがち" },
      { mbtiType: "ENFJ", tier: "D", comment: "みんなの平和を心から願う主人公" },
      { mbtiType: "INFP", tier: "D", comment: "妄想の中ならたまに狂気を発揮する" },
      { mbtiType: "ESFP", tier: "C", comment: "ノリと勢いで生きてるからサイコ要素はゼロ" },
      { mbtiType: "ISFP", tier: "C", comment: "マイペースなだけで他人に危害は加えない" },
      { mbtiType: "ESTJ", tier: "C", comment: "ルールに厳しすぎるだけで中身は常識人" },
      { mbtiType: "ISTJ", tier: "C", comment: "真面目すぎてサイコパスの真似すらできない" },
      { mbtiType: "ENFP", tier: "B", comment: "急に笑顔で残酷なことをさらっと言う" },
      { mbtiType: "INFJ", tier: "B", comment: "静かにターゲットの弱点を分析している" },
      { mbtiType: "ESTP", tier: "B", comment: "スリルを求めて倫理観をたまにバグらせる" },
      { mbtiType: "ISTP", tier: "B", comment: "他人の感情より自分の合理性を100%優先" },
      { mbtiType: "ENTJ", tier: "A", comment: "目的達成のためなら冷酷な決断も躊躇しない" },
      { mbtiType: "INTJ", tier: "A", comment: "脳内で完全犯罪のシミュレーションが終わってる" },
      { mbtiType: "ENTP", tier: "S", comment: "息をするように嘘をついて楽しそうに論破する" },
      { mbtiType: "INTP", tier: "S", comment: "倫理観すら「興味深い研究対象」として扱う真性" },
    ],
  },
  {
    id: "do_not_anger",
    title: "怒らせるとヤバいMBTI",
    tiktokCaption: "絶対に敵に回してはいけない。普段優しいのに怒らせたら人生終わる『隠れサイコパス』なMBTIは？\n圧倒的第1位はヤバすぎるのでプロフィールのリンクに答えを置きました。自分が当てはまってないか今すぐ確認して。\n\n#MBTI #MBTI診断 #怒らせてはいけない #サイコパス #16タイプ診断 #性格診断",
    videoType: "top5",
    entries: [
      { mbtiType: "INFP", tier: "5", comment: "第5位 INFP。怒っても泣く事しかできず、後で一人で病む無害な羊" },
      { mbtiType: "ESTP", tier: "4", comment: "第4位 ESTP。物理的に手が出るか、一生残るトラウマ級の暴言を吐く" },
      { mbtiType: "ENFJ", tier: "3", comment: "第3位 ENFJ。正義の御旗を掲げ、逃げ場のない正論で社会的に抹殺する" },
      { mbtiType: "ISFJ", tier: "2", comment: "第2位 ISFJ。あなたの罪を一生忘れず、無言の圧力で精神を削り取る" },
      { mbtiType: "INFJ", tier: "1", comment: "圧倒的第1位…文字数制限で書けないのでプロフリンクへ！" },
    ],
  },
  {
    id: "rich_potential",
    title: "お金持ちになりやすいランキング",
    tiktokCaption: "将来お金持ちになりやすいMBTI一覧💸 みんなは何位だった？コメントで教えてね！\n\n#MBTI #MBTI診断 #お金持ち #金運 #16タイプ診断 #社長 #性格診断",
    entries: [
      { mbtiType: "INFP", tier: "D", comment: "お金より心の豊かさを優先するため万年金欠" },
      { mbtiType: "ISFP", tier: "D", comment: "稼いだ分だけ趣味や推し活に全振りして溶かす" },
      { mbtiType: "ESFP", tier: "D", comment: "今が楽しければOK！宵越しの金は持たない" },
      { mbtiType: "ISFJ", tier: "D", comment: "コツコツ貯蓄するが、大きく増やすことは苦手" },
      { mbtiType: "ENFP", tier: "C", comment: "謎のビジネスに引っかかるが持ち前の運で乗り切る" },
      { mbtiType: "ESFJ", tier: "C", comment: "交際費で消えるが、人脈でお金に困らない" },
      { mbtiType: "INFJ", tier: "C", comment: "お金の亡者を軽蔑し、独自の理想郷に投資する" },
      { mbtiType: "ISTP", tier: "C", comment: "一攫千金を夢見て株やギャンブルで大勝負に出る" },
      { mbtiType: "ENFJ", tier: "B", comment: "卓越したカリスマ性で人とお金を引き寄せる" },
      { mbtiType: "ISTJ", tier: "B", comment: "絶対的な安定志向で、気がつけば堅実に金持ち" },
      { mbtiType: "INTP", tier: "B", comment: "天才的な頭脳で謎の仮想通貨や特許でボロ儲け" },
      { mbtiType: "ESTP", tier: "B", comment: "持ち前の嗅覚と行動力でビジネスチャンスを掴む" },
      { mbtiType: "ENTP", tier: "A", comment: "常識破りのアイデアと口のうまさで一気に成り上がる" },
      { mbtiType: "INTJ", tier: "A", comment: "完璧な資産運用モデルを構築し、寝てても金が増える" },
      { mbtiType: "ESTJ", tier: "S", comment: "圧倒的な実行力と管理能力で大企業のトップに立つ" },
      { mbtiType: "ENTJ", tier: "S", comment: "もはやお金を稼ぐこと自体がゲーム感覚の絶対王者" },
    ],
  },
  {
    id: "cheating_tendency",
    title: "浮気しやすい（危険度）ランキング",
    tiktokCaption: "絶対に付き合ってはいけない浮気男・浮気女ランキング💔 恋人のMBTI確認してみて…\n\n#MBTI #MBTI診断 #浮気 #恋愛 #16タイプ診断 #性格診断",
    entries: [
      { mbtiType: "ISFJ", tier: "D", comment: "浮気の概念が存在しない生きた天然保護記念物" },
      { mbtiType: "ISTJ", tier: "D", comment: "契約違反（浮気）を絶対に許さない真面目カンスト" },
      { mbtiType: "INFJ", tier: "D", comment: "裏切りに強い嫌悪感があり、一途すぎて重い" },
      { mbtiType: "INTJ", tier: "D", comment: "浮気する時間すら無駄と考える超・合理主義" },
      { mbtiType: "INFP", tier: "C", comment: "妄想の中では浮気三昧だが、現実はチキン" },
      { mbtiType: "ENFJ", tier: "C", comment: "みんなに優しすぎて勘違いさせやすいだけの罪なヤツ" },
      { mbtiType: "ESFJ", tier: "C", comment: "押しに弱くて流されやすいが、基本は超尽くす" },
      { mbtiType: "ENTJ", tier: "C", comment: "有能なパートナーを手に入れたら絶対手放さない" },
      { mbtiType: "INTP", tier: "B", comment: "興味本位で浮気したらどうなるか実験しようとする" },
      { mbtiType: "ESTJ", tier: "B", comment: "論理的にバレないと思ったら効率的に遊ぶ危険アリ" },
      { mbtiType: "ISFP", tier: "B", comment: "寂しさに弱く、その場の雰囲気に飲まれやすい" },
      { mbtiType: "ISTP", tier: "B", comment: "スリルのためだけに後腐れなくサクッと遊ぶ" },
      { mbtiType: "ENFP", tier: "A", comment: "新しい刺激と運命の出会いに弱く、常に心が迷子" },
      { mbtiType: "ENTP", tier: "A", comment: "口のうまさで複数同時進行し、バレても論破してくる" },
      { mbtiType: "ESFP", tier: "S", comment: "ノリと勢いで生きてるから、昨日も今日も明日も浮気" },
      { mbtiType: "ESTP", tier: "S", comment: "息をするようにナンパし、バレたら潔く散る遊び人" },
    ],
  },
  {
    id: "loner_potential",
    title: "友達が少ないぼっちランキング",
    tiktokCaption: "友達が少ないのは才能かもしれない…？🤔 ぼっち度ランキング！\n\n#MBTI #MBTI診断 #ぼっち #陰キャ #16タイプ診断 #性格診断",
    entries: [
      { mbtiType: "ESFP", tier: "D", comment: "息をするだけで友達が増える生粋の陽キャ" },
      { mbtiType: "ENFJ", tier: "D", comment: "どこに行っても教祖レベルで人が集まるカリスマ" },
      { mbtiType: "ESFJ", tier: "D", comment: "お世話焼きすぎて気づけば常に集団の中心にいる" },
      { mbtiType: "ENFP", tier: "D", comment: "誰にでも人懐っこい犬のような存在で愛される" },
      { mbtiType: "ESTP", tier: "C", comment: "ノリが良すぎて浅く広いヤバい人脈を持っている" },
      { mbtiType: "ENTP", tier: "C", comment: "ウザ絡みしすぎて嫌われるが、結局なぜか人がいる" },
      { mbtiType: "ENTJ", tier: "C", comment: "友達というより有能な「手下」をたくさん抱えている" },
      { mbtiType: "ISFJ", tier: "C", comment: "特定の仲良しグループに常に属している安定型" },
      { mbtiType: "ESTJ", tier: "B", comment: "厳しすぎて人が離れていき、気づけばぼっち" },
      { mbtiType: "ISFP", tier: "B", comment: "人といると疲れるので、自分から意図的にぼっちになる" },
      { mbtiType: "INFP", tier: "B", comment: "心を開くのに5世紀かかるため、真の友人は2人" },
      { mbtiType: "ISTP", tier: "B", comment: "「ひとりが一番楽」と悟りを開いたプロのソロプレイヤー" },
      { mbtiType: "ISTJ", tier: "A", comment: "休日も家から一歩も出ず、ルーティンだけを愛する" },
      { mbtiType: "INFJ", tier: "A", comment: "他人の嘘が透けて見えすぎて、人間関係をリセットしがち" },
      { mbtiType: "INTJ", tier: "S", comment: "「友達？そんな非生産的なもの必要か？」と本気で思ってる" },
      { mbtiType: "INTP", tier: "S", comment: "趣味に没頭しすぎて人間の言語とコミュニケーションを忘却" },
    ],
  },
  {
    id: "villain",
    title: "悪役(ヴィラン)向きな性格ランキング",
    tiktokCaption: "もしアニメの世界にいたら、一番ヤバい悪役になるのはこのタイプ😈\n\n#MBTI #MBTI診断 #ヴィラン #悪役 #16タイプ診断 #性格診断",
    entries: [
      { mbtiType: "ESFJ", tier: "D", comment: "悪人になりきれず、敵にすらおにぎりを握ってあげる" },
      { mbtiType: "ISFJ", tier: "D", comment: "「こんなことやっちゃダメだよぉ…」と最後まで止める役" },
      { mbtiType: "ENFP", tier: "D", comment: "悪の組織に入っても3日で飽きてヒーロー側に寝返る" },
      { mbtiType: "INFP", tier: "D", comment: "厨二病的な悪に憧れるが、アリを踏んだだけで凹む" },
      { mbtiType: "ESFP", tier: "C", comment: "悪の宴会部長。楽しければどっちの味方でもいい" },
      { mbtiType: "ENFJ", tier: "C", comment: "狂った正義感で「これが皆のため」と世界を滅ぼす系" },
      { mbtiType: "ISTJ", tier: "C", comment: "組織の経理や事務処理を淡々とこなす悪の社畜" },
      { mbtiType: "ISFP", tier: "C", comment: "ただ静かに暮らしたいだけなのに巻き込まれる闇の暗殺者" },
      { mbtiType: "ESTJ", tier: "B", comment: "圧倒的武力でヒーローを物理的に粉砕する脳筋幹部" },
      { mbtiType: "ESTP", tier: "B", comment: "戦闘狂。「お前強いな！俺と戦え！」系のトラブルメーカー" },
      { mbtiType: "ISTP", tier: "B", comment: "凄腕のスナイパー。お金さえ貰えれば誰でも撃つ" },
      { mbtiType: "INFJ", tier: "B", comment: "人間に絶望し「この腐った世界を一度リセットする」系ボス" },
      { mbtiType: "ENTP", tier: "A", comment: "ただ世界がカオスに陥るのを見て爆笑したいジョーカー" },
      { mbtiType: "INTP", tier: "A", comment: "マッドサイエンティストとしてヤバい兵器を趣味で作る" },
      { mbtiType: "ENTJ", tier: "S", comment: "「私がこの世界を支配する」圧倒的カリスマ魔王" },
      { mbtiType: "INTJ", tier: "S", comment: "ヒーローの動きを完全に予測し、闇の奥底から全てを操る黒幕" },
    ],
  },
  {
    id: "survival",
    title: "無人島サバイバル生き残りランキング",
    tiktokCaption: "無人島に飛ばされたら最後まで生き残れる最強のタイプは？🌴🥥\n\n#MBTI #MBTI診断 #サバイバル #無人島 #16タイプ診断 #性格診断",
    entries: [
      { mbtiType: "INFP", tier: "D", comment: "虫が無理すぎて開始3秒で泣きながらリタイア" },
      { mbtiType: "ISFJ", tier: "D", comment: "備蓄の食料をみんなに分け与えすぎて餓死する" },
      { mbtiType: "ENFP", tier: "D", comment: "毒キノコを「美味しそう！」と即座に食べてゲームオーバー" },
      { mbtiType: "ESFJ", tier: "D", comment: "「みんなで頑張ろう」と言うだけで実務的なスキルがない" },
      { mbtiType: "ESFP", tier: "C", comment: "無人島でもパーティーを開こうとして体力を消耗する" },
      { mbtiType: "ENFJ", tier: "C", comment: "謎のカリスマ性で宗教のような集落を作り上げる" },
      { mbtiType: "ISFP", tier: "C", comment: "自然と同化して砂浜で綺麗な貝殻を集めて現実逃避" },
      { mbtiType: "ENTP", tier: "C", comment: "「この島を脱出する革命的な方法」を語るだけで何もしない" },
      { mbtiType: "INFJ", tier: "B", comment: "未来を予知して安全な洞窟を確保し、精神力で耐え抜く" },
      { mbtiType: "INTJ", tier: "B", comment: "限られた資源を完璧な配分で管理する冷酷な司令塔" },
      { mbtiType: "INTP", tier: "B", comment: "落ちているゴミから浄水器や発電機をゼロから発明する" },
      { mbtiType: "ESTJ", tier: "B", comment: "超絶スパルタ軍隊式ルールを制定し、逆らう者を処罰する" },
      { mbtiType: "ENTJ", tier: "A", comment: "あっという間に無人島を近代化し、自分の帝国を築き上げる" },
      { mbtiType: "ESTP", tier: "A", comment: "猪を素手で狩り、野生の力を取り戻して無双する" },
      { mbtiType: "ISTJ", tier: "S", comment: "初日から完璧なルーティンを作り、10年後も同じ生活をしてる" },
      { mbtiType: "ISTP", tier: "S", comment: "ナイフ1本で家門・武器・罠を自作する最強の野生のプロ" },
    ],
  },
  {
    id: "dark_empathy",
    title: "人の心を操るのが上手いランキング",
    tiktokCaption: "気づかないうちに他人を洗脳して操っているヤバいタイプ…🧠👁️\n\n#MBTI #MBTI診断 #心理戦 #メンタル #16タイプ診断 #洗脳 #性格診断",
    entries: [
      { mbtiType: "ISFP", tier: "D", comment: "操るどころかいつも他人にブンブン振り回されている" },
      { mbtiType: "ISFJ", tier: "D", comment: "人を操るという発想自体がない。尽くすことしか知らない" },
      { mbtiType: "INFP", tier: "D", comment: "操る前に相手の悲しみに共感して一緒に泣いてしまう" },
      { mbtiType: "ISTJ", tier: "D", comment: "小手先の心理戦よりも、事実と証拠だけを信じる" },
      { mbtiType: "ESFP", tier: "C", comment: "操っている自覚はないが、愛嬌で結果的に人を動かす" },
      { mbtiType: "ESTJ", tier: "C", comment: "操るのではなく、腕力と職権で強制的に従わせる" },
      { mbtiType: "INTP", tier: "C", comment: "人間の感情に興味がなく、AIばかりイジっている" },
      { mbtiType: "ISTP", tier: "C", comment: "他人に干渉されるのが嫌いなので、他人も操作しない" },
      { mbtiType: "ESFJ", tier: "B", comment: "「あなたのために」という大義名分で外堀からジワジワ埋める" },
      { mbtiType: "ENFP", tier: "B", comment: "天性の人たらしで、相手に「自分が一番特別」と錯覚させる" },
      { mbtiType: "ESTP", tier: "B", comment: "相手の欲望を瞬時に見抜き、甘い言葉でそそのかす" },
      { mbtiType: "ENTJ", tier: "B", comment: "恐怖と報酬を使い分け、組織の人間を完璧にコントロール" },
      { mbtiType: "INTJ", tier: "A", comment: "相手の自己肯定感を破壊し、自分なしでは生きられなくする" },
      { mbtiType: "ENTP", tier: "A", comment: "言葉の魔術師。相手の価値観を根本からひっくり返す" },
      { mbtiType: "INFJ", tier: "S", comment: "心の一番深い闇に寄り添い、相手を完全な依存状態に落とす" },
      { mbtiType: "ENFJ", tier: "S", comment: "善意100％の笑顔のまま、集団全員を無意識のうちに洗脳" },
    ],
  },
];
